version: '3.1'
services:
  stats-server:
    build: ./stat-service/stat-server
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: explore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
